Component input handling
featuremine/yamal-python pull request #20
Opened 2022-08-26 18:13 UTC by fm-andres-rangel

2022-08-31 15:14 UTC, maxim-trokhimtchouk requested changes

2022-09-01 14:53 UTC, maxim-trokhimtchouk requested changes

2022-09-01 14:53 UTC, maxim-trokhimtchouk commented on yamal/__init__.py
> +                if super(type(self), self).__getattribute__("_reactor")() is None:
Should not need rector for __docs__

2022-09-01 14:55 UTC, maxim-trokhimtchouk approved these changes

2022-09-01 15:45 UTC, fm-fede-ravchina approved these changes

2022-09-01 15:46 UTC, maxim-trokhimtchouk approved these changes

2022-09-01 15:48 UTC, merged