Yamal run python implementation
featuremine/yamal-python pull request #30
Opened 2022-09-08 18:52 UTC by fm-andres-rangel

2022-09-08 19:16 UTC, fm-andres-rangel commented
https://featuremine.atlassian.net/browse/FM-739

2022-09-08 21:26 UTC, maxim-trokhimtchouk approved these changes

2022-09-08 21:34 UTC, maxim-trokhimtchouk requested changes
make yamal-run capabilities into a function.
reactor.deploy

2022-09-08 21:34 UTC, maxim-trokhimtchouk commented on yamal/yamal-run.py
> +    parser.add_argument("--sched", help="Run reactor in scheduled mode", action='store_true')
should be part of config

2022-09-08 21:35 UTC, maxim-trokhimtchouk commented on yamal/yamal-run.py
> +    parser.add_argument("--sched", help="Run reactor in scheduled mode", action='store_true')
Add a test in yamal.tests for reactor.deploy

2022-09-09 21:20 UTC, maxim-trokhimtchouk requested changes

2022-09-09 21:20 UTC, maxim-trokhimtchouk commented on scripts/yamal-run.py
> +        r.stop()
move that to deploy functionality

2022-09-09 21:20 UTC, maxim-trokhimtchouk commented on scripts/yamal-run.py
> +    r.deploy(args.config, args.module, args.component)
deploy is always for config

2022-09-12 17:01 UTC, merged